name: 'Pull request linter action'
description: "Lint your pull request name based on commitlint configuration"
author: 'Julien Karst'
inputs:
  configuration-path:
    description: 'The path for the commitlint configurations'
    required: false
    default: './commitlint.config.js'
runs:
  using: docker
  image: docker://wagoid/commitlint-github-action:2.1.1
  main: 'dist/index.js'
branding:
  icon: 'users'
  color: 'blue'
